# Copyright (c) 2022-2026, The Isaac Lab Project Developers.
# All rights reserved.
#
# SPDX-License-Identifier: BSD-3-Clause

"""Mimic data-generation config for So101Chess — auto-generated by create_task.py.

Mixes the task cfg with isaaclab's :class:`MimicEnvCfg`, which adds the
``datagen_config`` and ``subtask_configs`` fields consumed by the Mimic data
generation pipeline. The generated ``LeIsaac-SO101-Chess-v0-Mimic`` gym id (see this
package's ``__init__.py``) wires this cfg to ``BaseILEnv``.

The generator emits this file with ``datagen_config`` left at its
:class:`DataGenConfig` defaults and ``subtask_configs`` empty. Edit this file
to set ``datagen_config`` fields (e.g. ``name``, ``generation_num_trials``,
``seed``) and to populate ``self.subtask_configs[<eef_name>]`` with the
per-EEF ``SubTaskConfig`` list once the matching subtask termination signals
exist on the task cfg.
"""

from isaaclab.envs.mimic_env_cfg import MimicEnvCfg, SubTaskConfig
from isaaclab.utils import configclass

from .so101_chess_cfg import So101ChessTaskCfg


@configclass
class So101ChessMimicEnvCfg(So101ChessTaskCfg, MimicEnvCfg):
    """Mimic-enabled configuration for So101Chess."""

    def __post_init__(self):
        # Run both parents' post-inits first so all task scaffolding (scene,
        # actions, observations, eef_names → recorders) is in place.
        super().__post_init__()

        # Mimic generation should independently randomize every trial. The
        # annotated-demo recorder overrides these values back to success-gated
        # Sobol sampling so discarded human attempts can retry the same move.
        self.events.reset_sobol_chess_move.params["sampling_strategy"] = "random"
        self.events.reset_sobol_chess_move.params["advance_on_success_only"] = False

        # Keep the task's standard annotated recorder and make its dataset
        # contract explicit. Source demonstrations for this task intentionally
        # contain no image arrays.
        self.recorders.description = "SO-101 chess Mimic source demonstrations"
        self.recorders.fps = 60.0
        self.recorders.actions_frame = "robot_root"
        self.recorders.entity_order = ["chess"]
        self.recorders.articulation_order = ["robot"]
        self.recorders.camera_names = []
        self.datagen_config.generation_keep_failed = True
        # Hold the last source waypoint until success, with two seconds as a
        # safety cap if the position-driven arm never settles at home.
        self.datagen_config.generation_num_final_fixed_steps = 120
        # Destination-side subtasks use their own multi-object source-demo
        # selection. Both switches are required by the current generator to
        # permit fresh selection for each subtask in a single-arm task.
        self.datagen_config.generation_select_src_per_subtask = True
        self.datagen_config.generation_select_src_per_arm = True
        self.recorders.action_pose_component_slices = {
            "chess": {"pose": [0, 7], "gripper": [7, 8]},
        }

        # ── datagen_config ────────────────────────────────────────────────
        # Override DataGenConfig defaults as needed, e.g.:
        #     self.datagen_config.name = "demo_src_so101_chess_D0"
        #     self.datagen_config.generation_num_trials = 1000
        #     self.datagen_config.seed = 1

        # ── subtask_configs (per end-effector) ────────────────────────────
        # Populate once the matching subtask termination signals are wired
        # into the task cfg, e.g.:
        #     from isaaclab.envs.mimic_env_cfg import SubTaskConfig
        #     self.subtask_configs["gripper"] = [
        #         SubTaskConfig(object_ref="...", subtask_term_signal="..."),
        #         ...
        #     ]

        self.subtask_configs["chess"] = [
            SubTaskConfig(
                object_ref="active_piece",
                subtask_term_signal="move_over_source",
                subtask_term_offset_range=(5, 10),
                selection_strategy="nearest_neighbor_object",
                selection_strategy_kwargs={"nn_k": 3},
                action_noise=0.003,
                num_interpolation_steps=5,
                max_interpolation_translation_step=0.005,
                max_interpolation_rotation_step=0.035,
                num_fixed_steps=0,
                interpolate_gripper_action=False,
                apply_noise_during_interpolation=False,
                # Existing demonstrations were recorded while the robot was
                # still settling from the old all-zero reset.  Skip that
                # 20-frame transient now that reset starts at the demonstrated
                # leader pose.
                first_subtask_start_offset_range=(20, 20),
            ),
            SubTaskConfig(
                object_ref="active_piece",
                subtask_term_signal="grasp_object",
                subtask_term_offset_range=(2, 5),
                selection_strategy="nearest_neighbor_object",
                selection_strategy_kwargs={"nn_k": 3},
                action_noise=0.0,
                num_interpolation_steps=5,
                max_interpolation_translation_step=0.005,
                max_interpolation_rotation_step=0.035,
                num_fixed_steps=0,
                interpolate_gripper_action=False,
                apply_noise_during_interpolation=False,
            ),
            SubTaskConfig(
                object_ref="active_piece",
                subtask_term_signal="lift_object",
                subtask_term_offset_range=(0, 5),
                selection_strategy="nearest_neighbor_object",
                selection_strategy_kwargs={"nn_k": 3},
                action_noise=0.003,
                num_interpolation_steps=5,
                max_interpolation_translation_step=0.005,
                max_interpolation_rotation_step=0.035,
                num_fixed_steps=0,
                interpolate_gripper_action=False,
                apply_noise_during_interpolation=False,
            ),
            SubTaskConfig(
                object_ref="destination_square",
                subtask_term_signal="move_over_destination",
                subtask_term_offset_range=(0, 5),
                selection_strategy="nearest_neighbor_multi_object",
                selection_strategy_kwargs={
                    "object_names": ["active_piece", "destination_square"],
                    "object_weights": {"active_piece": 1.0, "destination_square": 1.0},
                    "pos_weight": 1.0,
                    "rot_weight": 0.0,
                    "aggregation": "max",
                    "nn_k": 3,
                },
                action_noise=0.003,
                num_interpolation_steps=10,
                max_interpolation_translation_step=0.005,
                max_interpolation_rotation_step=0.035,
                num_fixed_steps=0,
                interpolate_gripper_action=False,
                apply_noise_during_interpolation=False,
            ),
            SubTaskConfig(
                object_ref="destination_square",
                subtask_term_signal="place_object",
                subtask_term_offset_range=(0, 0),
                selection_strategy="nearest_neighbor_multi_object",
                selection_strategy_kwargs={
                    "object_names": ["active_piece", "destination_square"],
                    "object_weights": {"active_piece": 1.0, "destination_square": 1.0},
                    "pos_weight": 1.0,
                    "rot_weight": 0.0,
                    "aggregation": "max",
                    "nn_k": 3,
                },
                action_noise=0.0,
                num_interpolation_steps=5,
                max_interpolation_translation_step=0.005,
                max_interpolation_rotation_step=0.035,
                num_fixed_steps=0,
                interpolate_gripper_action=False,
                apply_noise_during_interpolation=False,
            ),
            SubTaskConfig(
                object_ref=None,
                subtask_term_signal="return_home",
                subtask_term_offset_range=(0, 0),
                selection_strategy="source_from_subtask",
                selection_strategy_kwargs={"source_subtask": "place_object"},
                action_noise=0.0,
                num_interpolation_steps=10,
                max_interpolation_translation_step=0.005,
                max_interpolation_rotation_step=0.035,
            ),

        ]
