# Copyright (c) 2022-2026, The Isaac Lab Project Developers.
# All rights reserved.
#
# SPDX-License-Identifier: BSD-3-Clause

"""Task config for So101Chess — auto-generated by create_task.py.

To customize further, edit this file directly after generation.
"""

import math
import os
from typing import Any

from pink.tasks import DampingTask, FrameTask

import isaaclab.envs.mdp as base_mdp
import isaaclab.sim as sim_utils
from isaaclab.assets import ArticulationCfg, AssetBaseCfg, RigidObjectCfg
from isaaclab.managers import EventTermCfg as EventTerm
from isaaclab.managers import ObservationGroupCfg as ObsGroup
from isaaclab.managers import ObservationTermCfg as ObsTerm
from isaaclab.managers import SceneEntityCfg
from isaaclab.managers import TerminationTermCfg as DoneTerm
from isaaclab.scene import InteractiveSceneCfg
from isaaclab.sensors import CameraCfg
from isaaclab.sim.spawners.from_files.from_files_cfg import UsdFileCfg
from isaaclab.utils import configclass
from pxr import Gf, PhysxSchema, Usd, UsdGeom, UsdPhysics

from so101_chess.assets import SCENES_DIR, OBJECTS_DIR, ROBOTS_DIR
from . import mdp
from so101_chess.base_il_env.base_il_env_cfg import BaseILEnvCfg

from single_so101_cubes_leisaac.robots.so101 import LEROBOT_SO101_SPAWN_CFG  # isort: skip
from isaaclab.controllers.pink_ik.pink_ik_cfg import PinkIKControllerCfg
from isaaclab.envs.mdp.actions.pink_actions_cfg import PinkInverseKinematicsActionCfg
from leisaac.devices.action_process import preprocess_device_action as preprocess_leisaac_device_action
from .mdp.pink_actions import So101PinkInverseKinematicsAction

# =====================================================================
# Asset paths — loaded from assets/<category>/so101_chess/
# =====================================================================
SCENE_USD_PATH = os.path.join(SCENES_DIR, "scena3.usd")
SO101_URDF_PATH = os.path.join(ROBOTS_DIR, "so101_wrist_mount_kinematics.urdf")
BISHOP_USD_PATH = os.path.join(OBJECTS_DIR, "chesspieces/Bishop_collision.usd")

KING_USD_PATH = os.path.join(OBJECTS_DIR, "chesspieces/King_collision.usd")

KNIGHT_USD_PATH = os.path.join(OBJECTS_DIR, "chesspieces/Knight_collision.usd")
PAWN_USD_PATH = os.path.join(OBJECTS_DIR, "chesspieces/Pawn_collision.usd")
QUEEN_USD_PATH = os.path.join(OBJECTS_DIR, "chesspieces/Queen_collision.usd")
ROOK_USD_PATH = os.path.join(OBJECTS_DIR, "chesspieces/Rook_collision.usd")

# =====================================================================
# Task targets — SINGLE SOURCE OF TRUTH for the "move one piece" episode.
#
# On every reset the ACTIVE_PIECE is placed on SOURCE_SQUARE, and that same
# SOURCE_SQUARE is painted RED (the piece to move). TARGET_SQUARE is painted
# GREEN (the destination). Because the placement event and the red-coloring
# event both reference SOURCE_SQUARE below, the red square can never drift out
# of sync with where the piece actually sits.
#
# These are hardcoded for now. To generate synthetic data, these are the values
# to drive with Sobol sampling (and, per-episode, ACTIVE_PIECE can be varied
# across the scene's pieces for domain randomization).
#
# Squares are (row, column) with 0 <= row, column <= 7.
# =====================================================================
ACTIVE_PIECE = "bishop_white"
SOURCE_SQUARE = (2, 2)  # RED  — where the piece to move currently sits
TARGET_SQUARE = (3, 3)  # GREEN — destination square (placeholder)

# The physical leader's centered wrist-roll reading needs this calibration-frame
# correction to align with the follower USD used by this task.
WRIST_ROLL_LEADER_OFFSET = -math.pi / 2.0
# Keep the simulated jaw in the tested range for grasping small rigid props.
GRIPPER_CLOSE_TARGET = -0.17
GRIPPER_OPEN_LIMIT = 1.74533
GRIPPER_OPEN_THRESHOLD = 0.3
# A real grasp arrests the jaw before it reaches GRIPPER_CLOSE_TARGET. Across
# all six pieces, the measured contact positions are -0.045 to 0.248 rad.
GRIPPER_CLOSED_THRESHOLD = 0.2
PLACEMENT_MAX_TILT_DEG = 45.0
RETURN_HOME_START_MAX_TILT_DEG = 75.0
RETURN_HOME_FINAL_MAX_TILT_DEG = 5.0
# Final poses in the source demonstrations cluster around this Cartesian pose
# in the robot-root frame. Pink may reach it through different valid joint
# configurations, so return-home must not require the reset joint angles.
RETURN_HOME_EEF_POS = (0.05, -0.12, 0.0135)
RETURN_HOME_EEF_THRESHOLD_M = (0.04, 0.04, 0.03)
RETURN_HOME_MIN_STEPS = 5
RETURN_HOME_MAX_STEP_M = 0.001


# Canonical start pose derived from the median first processed joint target in
# the 32 demonstrations in annotated_dataset_multi_object.hdf5.  The dataset's
# stored initial_state predates the first leader command and is therefore all
# zeros; using it would reproduce the unsafe zero-to-leader startup sweep.
DATASET_INITIAL_JOINT_POS = {
    "shoulder_pan": 1.526937,
    "shoulder_lift": -1.745329,
    "elbow_flex": 1.563270,
    "wrist_flex": 1.256591,
    "wrist_roll": -1.615815,
    "gripper": -0.169936,
}

# Keep the top-left square fixed in the robot's view while making the board
# smaller.  Square_0_0 is the far-left corner when viewed from the robot at
# +X, and the remaining squares extend from it toward the robot and to the
# right.  Re-spacing from this anchor therefore makes the near edge recede.
CHESSBOARD_SQUARE_SIZE = 0.0333
CHESSBOARD_ANCHOR_SQUARE = (0, 0)
CHESSBOARD_BORDER_SIZE = 0.30
# Intentionally unchanged: mass tuning (remedy 6) is out of scope for now.
PIECE_MASS_KG = 0.02

# Free pieces need only a small solver budget while resting on the board. The
# robot keeps its imported 16/4 budget, which is also the budget used when the
# annotated demonstrations were recorded. PhysX uses that larger request once
# a piece joins the robot's contact island during a grasp.
PIECE_SOLVER_POSITION_ITERATIONS = 2
PIECE_SOLVER_VELOCITY_ITERATIONS = 1
# The imported follower caps the gripper at 10 N.m.  Its position drive is
# already saturated while holding a chess piece, so raise the cap locally to
# increase squeeze/retention force without changing its response gains.
GRIPPER_EFFORT_LIMIT = 20.0


# The scene USD was authored with contact offsets and torsional-friction radii
# that are larger than the chessboard itself. Override them before PhysX first
# parses the stage, and use one valid material for every static scene collider.
SCENE_PHYSICS_MATERIAL = sim_utils.RigidBodyMaterialCfg(
    static_friction=0.8,
    dynamic_friction=0.6,
    restitution=0.0,
    friction_combine_mode="average",
    restitution_combine_mode="min",
)
SCENE_COLLISION_PROPERTIES = sim_utils.CollisionPropertiesCfg(
    contact_offset=0.0005,
    rest_offset=0.0,
    torsional_patch_radius=0.0,
    min_torsional_patch_radius=0.0,
)


def _set_canonical_cube_extent(prim) -> None:
    """Make a Cube's authored extent agree with its local size.

    The source board authored an already-scaled Z extent and then scaled that
    extent a second time in USD.  PhysX uses the Cube size while BBox queries
    use the stale extent, which made resets target a point inside the board.
    """
    cube = UsdGeom.Cube(prim)
    size = cube.GetSizeAttr().Get()
    if size is None:
        size = 2.0
    half_size = 0.5 * float(size)
    cube.CreateExtentAttr().Set(
        [
            Gf.Vec3f(-half_size, -half_size, -half_size),
            Gf.Vec3f(half_size, half_size, half_size),
        ]
    )


def _resize_chessboard(scene_prim) -> None:
    """Resize the visuals and replace 65 tiled colliders with one surface."""
    stage = scene_prim.GetStage()
    board_path = scene_prim.GetPath().AppendChild("ChessBoard")
    anchor_row, anchor_col = CHESSBOARD_ANCHOR_SQUARE

    def _translation(row: int, col: int):
        square_path = board_path.AppendChild(f"Square_{row}_{col}")
        square = stage.GetPrimAtPath(square_path)
        if not square.IsValid():
            raise RuntimeError(f"Chessboard square does not exist: {square_path}")
        value = square.GetAttribute("xformOp:translate").Get()
        if value is None:
            raise RuntimeError(f"Chessboard square has no translation: {square_path}")
        return value

    anchor_position = _translation(anchor_row, anchor_col)
    row_step = _translation(anchor_row + 1, anchor_col) - anchor_position
    col_step = _translation(anchor_row, anchor_col + 1) - anchor_position
    if row_step.GetLength() == 0.0 or col_step.GetLength() == 0.0:
        raise RuntimeError("Chessboard row/column spacing must be non-zero.")
    row_direction = row_step / row_step.GetLength()
    col_direction = col_step / col_step.GetLength()

    # Center the yellow BasePlate so its margin is equal on all four sides.
    board_center = (
        anchor_position
        + row_direction * (3.5 * CHESSBOARD_SQUARE_SIZE)
        + col_direction * (3.5 * CHESSBOARD_SQUARE_SIZE)
    )
    base_plate_path = board_path.AppendChild("BasePlate")
    base_plate = stage.GetPrimAtPath(base_plate_path)
    base_plate_translate = base_plate.GetAttribute("xformOp:translate")
    base_plate_scale = base_plate.GetAttribute("xformOp:scale")
    base_plate_position = base_plate_translate.Get()
    base_plate_size = base_plate_scale.Get()
    if base_plate_position is None:
        raise RuntimeError(f"Chessboard base plate has no translation: {base_plate_path}")
    if base_plate_size is None:
        raise RuntimeError(f"Chessboard base plate has no scale: {base_plate_path}")
    base_plate_translate.Set(Gf.Vec3d(board_center[0], board_center[1], base_plate_position[2]))
    base_plate_scale.Set(Gf.Vec3d(CHESSBOARD_BORDER_SIZE, CHESSBOARD_BORDER_SIZE, base_plate_size[2]))
    _set_canonical_cube_extent(base_plate)
    if base_plate.HasAPI(UsdPhysics.CollisionAPI):
        UsdPhysics.CollisionAPI(base_plate).GetCollisionEnabledAttr().Set(False)
    if base_plate.HasAPI(UsdPhysics.RigidBodyAPI):
        UsdPhysics.RigidBodyAPI(base_plate).GetRigidBodyEnabledAttr().Set(False)

    square_thickness = None
    square_center_z = None

    for row in range(8):
        for col in range(8):
            square_path = board_path.AppendChild(f"Square_{row}_{col}")
            square = stage.GetPrimAtPath(square_path)
            translate_attr = square.GetAttribute("xformOp:translate")
            scale_attr = square.GetAttribute("xformOp:scale")
            scale = scale_attr.Get()
            if scale is None:
                raise RuntimeError(f"Chessboard square has no scale: {square_path}")

            position = (
                anchor_position
                + row_direction * ((row - anchor_row) * CHESSBOARD_SQUARE_SIZE)
                + col_direction * ((col - anchor_col) * CHESSBOARD_SQUARE_SIZE)
            )
            translate_attr.Set(position)
            scale_attr.Set(Gf.Vec3d(CHESSBOARD_SQUARE_SIZE, CHESSBOARD_SQUARE_SIZE, scale[2]))
            _set_canonical_cube_extent(square)
            if square.HasAPI(UsdPhysics.CollisionAPI):
                UsdPhysics.CollisionAPI(square).GetCollisionEnabledAttr().Set(False)
            if square.HasAPI(UsdPhysics.RigidBodyAPI):
                UsdPhysics.RigidBodyAPI(square).GetRigidBodyEnabledAttr().Set(False)
            if square_thickness is None:
                square_thickness = abs(float(scale[2]))
                square_center_z = float(position[2])

    if square_thickness is None or square_center_z is None:
        raise RuntimeError("Chessboard contains no squares from which to build its surface collider.")

    # A single primitive eliminates all internal edges between the 64 visual
    # squares.  It is invisible but remains the only physical board surface.
    surface_path = board_path.AppendChild(mdp.BOARD_SURFACE_COLLIDER_NAME)
    surface = UsdGeom.Cube.Define(stage, surface_path)
    surface.CreateSizeAttr(1.0)
    _set_canonical_cube_extent(surface.GetPrim())
    surface_xform = UsdGeom.Xformable(surface)
    surface_xform.AddTranslateOp().Set(
        Gf.Vec3d(float(board_center[0]), float(board_center[1]), square_center_z)
    )
    surface_xform.AddScaleOp().Set(
        Gf.Vec3d(
            8.0 * CHESSBOARD_SQUARE_SIZE,
            8.0 * CHESSBOARD_SQUARE_SIZE,
            square_thickness,
        )
    )
    UsdGeom.Imageable(surface.GetPrim()).MakeInvisible()
    sim_utils.define_collision_properties(str(surface_path), SCENE_COLLISION_PROPERTIES)


@sim_utils.clone
def spawn_scene_usd(
    prim_path: str,
    cfg: UsdFileCfg,
    translation: tuple[float, float, float] | None = None,
    orientation: tuple[float, float, float, float] | None = None,
    **kwargs,
):
    """Spawn the resized scene and replace invalid collider materials."""
    prim = sim_utils.spawn_from_usd(
        prim_path,
        cfg,
        translation=translation,
        orientation=orientation,
        **kwargs,
    )
    _resize_chessboard(prim)
    material_path = f"{prim_path}/physicsMaterial"
    SCENE_PHYSICS_MATERIAL.func(material_path, SCENE_PHYSICS_MATERIAL)
    sim_utils.bind_physics_material(prim_path, material_path)
    return prim


@sim_utils.clone
def _spawn_rigid_usd(
    prim_path: str,
    cfg: UsdFileCfg,
    translation: tuple[float, float, float] | None = None,
    orientation: tuple[float, float, float, float] | None = None,
    **kwargs,
):
    """Spawn a rigid piece while preserving its authored collision hierarchy."""
    rigid_props = cfg.rigid_props or sim_utils.RigidBodyPropertiesCfg()
    mass_props = cfg.mass_props or sim_utils.MassPropertiesCfg(mass=PIECE_MASS_KG)

    # spawn_from_usd can modify existing nested colliders, but cannot add a
    # missing rigid body or mass API.
    cfg.rigid_props = None
    cfg.mass_props = None
    try:
        prim = sim_utils.spawn_from_usd(
            prim_path,
            cfg,
            translation=translation,
            orientation=orientation,
            **kwargs,
        )
    finally:
        cfg.rigid_props = rigid_props
        cfg.mass_props = mass_props

    sim_utils.define_rigid_body_properties(prim_path, rigid_props)
    sim_utils.define_mass_properties(prim_path, mass_props)
    # Keep one collision hierarchy per piece and force its authored collision
    # meshes through PhysX convex decomposition. The former compound of 4--6
    # overlapping primitives created one persistent contact pair per primitive
    # against the gripper SDF and reduced throughput to roughly 2 FPS.
    for child in Usd.PrimRange(prim):
        if not child.HasAPI(UsdPhysics.CollisionAPI):
            continue
        approximation = child.GetAttribute("physics:approximation")
        if approximation.IsValid():
            approximation.Set("convexDecomposition")

    # Speculative CCD catches fast contacts without the extra substeps of
    # sweep-based CCD.  Velocity and impulse caps below remain the backstop.
    physx_body = PhysxSchema.PhysxRigidBodyAPI.Apply(prim)
    physx_body.CreateEnableSpeculativeCCDAttr().Set(True)
    material_path = f"{prim_path}/physicsMaterial"
    PIECE_PHYSICS_MATERIAL.func(material_path, PIECE_PHYSICS_MATERIAL)
    sim_utils.bind_physics_material(prim_path, material_path)
    return prim


PIECE_RIGID_PROPERTIES = sim_utils.RigidBodyPropertiesCfg(
    disable_gravity=False,
    linear_damping=0.1,
    angular_damping=0.1,
    max_linear_velocity=2.0,
    max_angular_velocity=720.0,
    max_depenetration_velocity=0.2,
    solver_position_iteration_count=PIECE_SOLVER_POSITION_ITERATIONS,
    solver_velocity_iteration_count=PIECE_SOLVER_VELOCITY_ITERATIONS,
)
PIECE_COLLISION_PROPERTIES = sim_utils.CollisionPropertiesCfg(
    collision_enabled=True,
    contact_offset=0.001,
    rest_offset=0.0,
    torsional_patch_radius=0.003,
    min_torsional_patch_radius=0.001,
)


PIECE_PHYSICS_MATERIAL = sim_utils.RigidBodyMaterialCfg(
    static_friction=0.6,
    dynamic_friction=0.5,
    restitution=0.0,
    friction_combine_mode="average",
    restitution_combine_mode="min",
)


def _chess_piece_spawn_cfg(usd_path: str) -> UsdFileCfg:
    """Build the common, contact-stable spawn config for a chess piece."""
    return UsdFileCfg(
        func=_spawn_rigid_usd,
        usd_path=usd_path,
        scale=(0.0008, 0.0008, 0.0008),
        rigid_props=PIECE_RIGID_PROPERTIES,
        mass_props=sim_utils.MassPropertiesCfg(mass=PIECE_MASS_KG),
        collision_props=PIECE_COLLISION_PROPERTIES,
    )


# Keep this task's contact tuning local.  The imported robot configuration is
# shared by other SO-101 tasks and should not be weakened globally.
SO101_CHESS_ROBOT_CFG = LEROBOT_SO101_SPAWN_CFG.copy()
SO101_CHESS_ROBOT_CFG.spawn.rigid_props.max_depenetration_velocity = 0.5
SO101_CHESS_ROBOT_CFG.spawn.collision_props.contact_offset = 0.001
SO101_CHESS_ROBOT_CFG.spawn.collision_props.rest_offset = 0.0
# Keep the imported velocity limit and position-drive gains, but give this
# task's gripper more authority to retain the convex-decomposed pieces.
SO101_CHESS_ROBOT_CFG.actuators["gripper"].effort_limit_sim = GRIPPER_EFFORT_LIMIT


def attach_cameras(scene_cfg) -> None:
    """Attach cameras to a So101Chess scene cfg.

    Kept as a module-level helper so the teleop launcher can re-attach the
    cameras after IsaacLab's XR pipeline strips CameraCfg attributes via
    ``remove_camera_configs``. Called from ``__post_init__`` for normal runs.
    """
    scene_cfg.top_camera = CameraCfg(
        prim_path="{ENV_REGEX_NS}/top_camera",
        update_period=0.0,
        height=480,
        width=640,
        data_types=["rgb"],
        spawn=sim_utils.PinholeCameraCfg(
            focal_length=12.0,
            focus_distance=400.0,
            horizontal_aperture=20.955,
            clipping_range=(0.05, 10.0),
        ),
        offset=CameraCfg.OffsetCfg(
            pos=(-0.2294,-0.05, 1.20),
            rot=(0.6743, 0.212,-0.212 ,-0.6743),
            convention="opengl",
        ),
    )
    scene_cfg.right_wrist_camera = CameraCfg(
        prim_path="{ENV_REGEX_NS}/Scene/arm/gripper_link/right_wrist_camera",
        update_period=0.0,
        height=480,
        width=640,
        data_types=["rgb"],
        spawn=None,
    )

# =====================================================================
# 1) SCENE
# =====================================================================
@configclass
class So101ChessSceneCfg(InteractiveSceneCfg):
    """Scene configuration for So101Chess."""

    scene: AssetBaseCfg = AssetBaseCfg(
        prim_path="{ENV_REGEX_NS}/Scene",
        spawn=UsdFileCfg(
            func=spawn_scene_usd,
            usd_path=SCENE_USD_PATH,
            scale=(1.0, 1.0, 1.0),
            collision_props=SCENE_COLLISION_PROPERTIES,
        ),
        init_state=AssetBaseCfg.InitialStateCfg(pos=(0.0, 0.0, 0.0), rot=(1.0, 0.0, 0.0, 0.0)),
    )

    robot: ArticulationCfg = SO101_CHESS_ROBOT_CFG.replace(
        prim_path="{ENV_REGEX_NS}/Scene/arm",
        init_state=ArticulationCfg.InitialStateCfg(
            pos=(0.35, 0.0, 0.75),
            rot=(0.0, 0.0, 0.0, 1.0),
            joint_pos=DATASET_INITIAL_JOINT_POS,
        ),
    )

    rook_white: RigidObjectCfg = RigidObjectCfg(
        prim_path="{ENV_REGEX_NS}/rook",
        spawn=_chess_piece_spawn_cfg(ROOK_USD_PATH),
        init_state=RigidObjectCfg.InitialStateCfg(pos=(-0.19, -0.06, 0.8), rot=(1.0, 0.0, 0.0, 0.0)),
    )

    knight_white: RigidObjectCfg = RigidObjectCfg(
        prim_path="{ENV_REGEX_NS}/knight",
        spawn=_chess_piece_spawn_cfg(KNIGHT_USD_PATH),
        init_state=RigidObjectCfg.InitialStateCfg(pos=(-0.15, -0.12, 0.8), rot=(1.0, 0.0, 0.0, 0.0)),
    )

    bishop_white: RigidObjectCfg = RigidObjectCfg(
        prim_path="{ENV_REGEX_NS}/bishop",
        spawn=_chess_piece_spawn_cfg(BISHOP_USD_PATH),
        init_state=RigidObjectCfg.InitialStateCfg(pos=(-0.16, 0.08, 0.8), rot=(1.0, 0.0, 0.0, 0.0)),
    )

    queen_white: RigidObjectCfg = RigidObjectCfg(
        prim_path="{ENV_REGEX_NS}/queen",
        spawn=_chess_piece_spawn_cfg(QUEEN_USD_PATH),
        init_state=RigidObjectCfg.InitialStateCfg(pos=(-0.113, 0.12, 0.8), rot=(1.0, 0.0, 0.0, 0.0)),
    )

    king_white: RigidObjectCfg = RigidObjectCfg(
        prim_path="{ENV_REGEX_NS}/king",
        spawn=_chess_piece_spawn_cfg(KING_USD_PATH),
        init_state=RigidObjectCfg.InitialStateCfg(pos=(-0.08, 0.18, 0.8), rot=(1.0, 0.0, 0.0, 0.0)),
    )

    pawn_white: RigidObjectCfg = RigidObjectCfg(
        prim_path="{ENV_REGEX_NS}/pawn",
        spawn=_chess_piece_spawn_cfg(PAWN_USD_PATH),
        init_state=RigidObjectCfg.InitialStateCfg(pos=(-0.12, 0.0, 0.8), rot=(1.0, 0.0, 0.0, 0.0)),
    )

    # Separate bodies allow both piece color and board occupancy to vary.
    rook_black: RigidObjectCfg = RigidObjectCfg(
        prim_path="{ENV_REGEX_NS}/rook_black", spawn=_chess_piece_spawn_cfg(ROOK_USD_PATH),
        init_state=RigidObjectCfg.InitialStateCfg(pos=(10.0, 10.0, 0.8), rot=(1.0, 0.0, 0.0, 0.0)),
    )
    knight_black: RigidObjectCfg = RigidObjectCfg(
        prim_path="{ENV_REGEX_NS}/knight_black", spawn=_chess_piece_spawn_cfg(KNIGHT_USD_PATH),
        init_state=RigidObjectCfg.InitialStateCfg(pos=(10.2, 10.0, 0.8), rot=(1.0, 0.0, 0.0, 0.0)),
    )
    bishop_black: RigidObjectCfg = RigidObjectCfg(
        prim_path="{ENV_REGEX_NS}/bishop_black", spawn=_chess_piece_spawn_cfg(BISHOP_USD_PATH),
        init_state=RigidObjectCfg.InitialStateCfg(pos=(10.4, 10.0, 0.8), rot=(1.0, 0.0, 0.0, 0.0)),
    )
    queen_black: RigidObjectCfg = RigidObjectCfg(
        prim_path="{ENV_REGEX_NS}/queen_black", spawn=_chess_piece_spawn_cfg(QUEEN_USD_PATH),
        init_state=RigidObjectCfg.InitialStateCfg(pos=(10.6, 10.0, 0.8), rot=(1.0, 0.0, 0.0, 0.0)),
    )
    king_black: RigidObjectCfg = RigidObjectCfg(
        prim_path="{ENV_REGEX_NS}/king_black", spawn=_chess_piece_spawn_cfg(KING_USD_PATH),
        init_state=RigidObjectCfg.InitialStateCfg(pos=(10.8, 10.0, 0.8), rot=(1.0, 0.0, 0.0, 0.0)),
    )
    pawn_black: RigidObjectCfg = RigidObjectCfg(
        prim_path="{ENV_REGEX_NS}/pawn_black", spawn=_chess_piece_spawn_cfg(PAWN_USD_PATH),
        init_state=RigidObjectCfg.InitialStateCfg(pos=(11.0, 10.0, 0.8), rot=(1.0, 0.0, 0.0, 0.0)),
    )

# =====================================================================
# 2) ACTIONS
# =====================================================================
@configclass
class So101ChessActionsCfg:
    """Pink IK pose and gripper action for So101Chess."""

    arm_action = PinkInverseKinematicsActionCfg(
        class_type=So101PinkInverseKinematicsAction,
        asset_name="robot",
        pink_controlled_joint_names=[
            "shoulder_pan",
            "shoulder_lift",
            "elbow_flex",
            "wrist_flex",
            "wrist_roll",
        ],
        hand_joint_names=["gripper"],
        target_eef_link_names={"chess": "gripper_frame_link"},
        controller=PinkIKControllerCfg(
            urdf_path=SO101_URDF_PATH,
            mesh_path=None,
            num_hand_joints=1,
            variable_input_tasks=[
                # The five-DoF arm cannot satisfy an arbitrary 6D pose.
                # Prioritize Cartesian position while retaining orientation as
                # a soft objective and damping singular configurations.
                FrameTask(
                    "gripper_frame_link",
                    position_cost=10.0,
                    orientation_cost=0.1,
                    lm_damping=0.01,
                    gain=1.0,
                ),
                DampingTask(cost=0.01),
            ],
            fixed_input_tasks=[],
            articulation_name="robot",
            base_link_name="base_link",
            show_ik_warnings=True,
            fail_on_joint_limit_violation=False,
        ),
        enable_gravity_compensation=False,
    )


@configclass
class So101ChessLeaderActionsCfg:
    """Ordered joint targets produced by a physical LeRobot SO-101 leader."""

    # These are absolute joint targets.  In particular, use_default_offset
    # must stay False: enabling it would add DATASET_INITIAL_JOINT_POS to every
    # leader reading instead of making the follower match the leader.
    arm_action = mdp.SlewRateLimitedJointPositionActionCfg(
        asset_name="robot",
        joint_names=["shoulder_pan", "shoulder_lift", "elbow_flex", "wrist_flex", "wrist_roll"],
        scale=1.0,
        offset={"wrist_roll": WRIST_ROLL_LEADER_OFFSET},
        use_default_offset=False,
        preserve_order=True,
        max_velocity=2.0,
        block_downward_near_board=True,
        eef_body_name="gripper_frame_link",
        gripper_joint_name="gripper",
        gripper_closed_threshold=GRIPPER_CLOSED_THRESHOLD,
        board_contact_clearance=0.002,
    )

    gripper_action = mdp.JointPositionActionCfg(
        asset_name="robot",
        joint_names=["gripper"],
        scale=1.0,
        offset=0.0,
        clip={"gripper": (GRIPPER_CLOSE_TARGET, GRIPPER_OPEN_LIMIT)},
        use_default_offset=False,
        preserve_order=True,
    )

# =====================================================================
# 3) OBSERVATIONS
# =====================================================================
@configclass
class So101ChessObservationsCfg:
    """Observations for So101Chess."""

    @configclass
    class PolicyCfg(ObsGroup):
        actions = ObsTerm(func=mdp.last_action)
        robot_joint_pos = ObsTerm(
            func=base_mdp.joint_pos,
            params={"asset_cfg": SceneEntityCfg("robot")},
        )
        # End-effector pose observations.
        # `BaseILEnv.get_robot_eef_pose` reads these out of obs_buf by the
        # `{eef_name}_eef_pos` / `{eef_name}_eef_quat` keys — names must match.
        chess_eef_pos = ObsTerm(func=mdp.get_eef_pos, params={"link_name": "gripper_frame_link"})
        chess_eef_quat = ObsTerm(func=mdp.get_eef_quat, params={"link_name": "gripper_frame_link"})

        def __post_init__(self):
            self.enable_corruption = False
            self.concatenate_terms = False

    @configclass
    class SubtaskTermsCfg(ObsGroup):
        """Chess-move subtask predicates consumed by the Mimic recorder."""

        move_over_source = ObsTerm(
            func=mdp.move_over_source_done,
            params={
                "eef_link": "gripper_frame_link",
                "dist_threshold": 0.08,
                "z_offset": 0.10,
                "gripper_joint_pattern": "gripper",
                "gripper_open_threshold": GRIPPER_OPEN_THRESHOLD,
                "piece_source_xy_threshold": 0.05,
                "piece_source_z_threshold": 0.03,
                "piece_max_tilt_deg": 30.0,
                "max_steps": 300,
            },
        )
        grasp_object = ObsTerm(
            func=mdp.grasp_object_done,
            params={
                "eef_link": "gripper_frame_link",
                "dist_threshold": 0.08,
                "gripper_joint_pattern": "gripper",
                "gripper_closed_threshold": GRIPPER_CLOSED_THRESHOLD,
                "piece_source_xy_threshold": 0.08,
                "piece_source_z_threshold": 0.06,
                "piece_max_tilt_deg": 30.0,
                "max_steps": 300,
            },
        )
        lift_object = ObsTerm(
            func=mdp.lift_object_done,
            params={
                "eef_link": "gripper_frame_link",
                "object_name": None,
                "source_dist_threshold": 0.08,
                "lift_z_offset": 0.08,
                "gripper_joint_pattern": "gripper",
                "gripper_closed_threshold": GRIPPER_CLOSED_THRESHOLD,
                "gripper_open_threshold": GRIPPER_OPEN_THRESHOLD,
                "gripper_lost_dist_threshold": 0.15,
                "piece_drop_z_threshold": 0.03,
                "piece_max_tilt_deg": 45.0,
                "max_steps": 300,
            },
        )
        move_over_destination = ObsTerm(
            func=mdp.move_over_destination_done,
            params={
                "eef_link": "gripper_frame_link",
                "dist_threshold": 0.08,
                "gripper_joint_pattern": "gripper",
                "gripper_open_threshold": GRIPPER_OPEN_THRESHOLD,
                "gripper_lost_dist_threshold": 0.15,
                "piece_drop_z_threshold": 0.05,
                "piece_drop_xy_radius": 0.5,
                "min_transport_height": 0.04,
                "target_xy_threshold": 0.08,
                "max_steps": 300,
            },
        )
        place_object = ObsTerm(
            func=mdp.place_object_done,
            params={
                "eef_link": "gripper_frame_link",
                "object_name": None,
                "target_dist_threshold": 0.08,
                "gripper_joint_pattern": "gripper",
                "gripper_closed_threshold": GRIPPER_CLOSED_THRESHOLD,
                "upright_angle_deg_min": -PLACEMENT_MAX_TILT_DEG,
                "upright_angle_deg_max": PLACEMENT_MAX_TILT_DEG,
                "gripper_lost_dist_threshold": 0.15,
                "release_xy_threshold": 0.02,
                "release_z_threshold": 0.02,
                "piece_drop_z_threshold": 0.05,
                "piece_drop_xy_radius": 0.5,
                "max_steps": 300,
            },
        )
        return_home = ObsTerm(
            func=mdp.return_home_done,
            params={
                "object_name": None,
                "eef_link": "gripper_frame_link",
                "home_pos": RETURN_HOME_EEF_POS,
                "home_threshold": RETURN_HOME_EEF_THRESHOLD_M,
                "min_home_steps": RETURN_HOME_MIN_STEPS,
                "max_home_step_m": RETURN_HOME_MAX_STEP_M,
                "gripper_joint_pattern": "gripper",
                "gripper_closed_threshold": GRIPPER_CLOSED_THRESHOLD,
                "target_xy_threshold": 0.02,
                "target_z_threshold": 0.02,
                "return_start_max_tilt_deg": RETURN_HOME_START_MAX_TILT_DEG,
                "piece_max_tilt_deg": RETURN_HOME_FINAL_MAX_TILT_DEG,
                "max_steps": 300,
            },
        )

        def __post_init__(self):
            self.enable_corruption = False
            self.concatenate_terms = False

    policy: PolicyCfg = PolicyCfg()
    subtask_terms: SubtaskTermsCfg = SubtaskTermsCfg()


# =====================================================================
# 4) EVENTS & TERMINATIONS
# =====================================================================
@configclass
class So101ChessEventCfg:
    reset_all = None

    reset_robot = EventTerm(
        func=mdp.reset_robot_to_default,
        mode="reset",
        params={"asset_cfg": SceneEntityCfg("robot"), "reset_joint_targets": True},
    )

    reset_sobol_chess_move = EventTerm(
        func=mdp.sample_chess_move_reset,
        mode="reset",
        params={
            "piece_names": [
                "pawn_white",
                "rook_white",
                "knight_white",
                "bishop_white",
                "queen_white",
                "king_white",
                "pawn_black",
                "rook_black",
                "knight_black",
                "bishop_black",
                "queen_black",
                "king_black",
            ],
            "seed": 0,
            "board_size": 8,
            "z_offset": 0.001,
            "advance_on_success_only": True,
            "sampling_strategy": "sobol",
            "min_pieces": 1,
            "max_pieces": 6,
        },
    )

    randomize_appearance = EventTerm(
        func=mdp.randomize_chess_appearance,
        mode="reset",
        params={
            "light_intensity_range": (0.4, 2.0),
            "light_temperature_range": (2500.0, 7000.0),
        },
    )

    reset_chess_subtask_stage = EventTerm(
        func=mdp.reset_chess_subtask_stage,
        mode="reset",
    )

    reset_chess_hold_counter = EventTerm(
        func=mdp.reset_chess_hold_counter,
        mode="reset",
    )

    # Backward-compatible hardcoded reset kept as a static default for debug.


@configclass
class So101ChessTerminationsCfg:
    time_out = DoneTerm(func=mdp.time_out, time_out=True)

    success = DoneTerm(
        func=mdp.chess_move_success,
        params={
            "target_xy_threshold": 0.02,
            "target_z_threshold": 0.02,
            "max_tilt_deg": RETURN_HOME_FINAL_MAX_TILT_DEG,
            "return_start_max_tilt_deg": RETURN_HOME_START_MAX_TILT_DEG,
            "home_eef_link": "gripper_frame_link",
            "home_pos": RETURN_HOME_EEF_POS,
            "home_threshold": RETURN_HOME_EEF_THRESHOLD_M,
            "min_home_steps": RETURN_HOME_MIN_STEPS,
            "max_home_step_m": RETURN_HOME_MAX_STEP_M,
            "gripper_joint_pattern": "gripper",
            "gripper_closed_threshold": GRIPPER_CLOSED_THRESHOLD,
        },
    )

    failed = DoneTerm(func=mdp.chess_move_failed)


# =====================================================================
# 5) FINAL CONFIG
# =====================================================================
@configclass
class So101ChessTaskCfg(BaseILEnvCfg):

    scene: So101ChessSceneCfg = So101ChessSceneCfg(
        num_envs=1, env_spacing=2.5, replicate_physics=True
    )
    observations: So101ChessObservationsCfg = So101ChessObservationsCfg()
    actions: So101ChessActionsCfg = So101ChessActionsCfg()
    events: So101ChessEventCfg = So101ChessEventCfg()
    terminations: So101ChessTerminationsCfg = So101ChessTerminationsCfg()

    # Used by LeIsaac's teleoperation loop when resetting the physical leader.
    dynamic_reset_gripper_effort_limit: bool = False
    # Pinocchio must be imported before Isaac Sim when the default Pink action
    # configuration is used.
    requires_pinocchio: bool = True

    def use_teleop_device(self, teleop_device: str) -> None:
        """Select the six-joint action layout required by the SO-101 leader."""
        if teleop_device != "so101leader":
            raise ValueError(
                "So101Chess is configured for LeIsaac's 'so101leader' physical controller."
            )
        self.task_type = teleop_device
        self.actions = So101ChessLeaderActionsCfg()

    def preprocess_device_action(self, action: dict[str, Any], teleop_device) -> Any:
        """Map calibrated leader motor readings to ordered follower joint targets."""
        return preprocess_leisaac_device_action(action, teleop_device)

    def __post_init__(self):
        # EEF list — picked up by BaseILEnv methods and wired into the
        # recorder's entity_order by BaseILEnvCfg.__post_init__. Set before
        # super() so the base post-init sees it.
        self.eef_names = ["chess"]

        # Per-EEF action tensor layout — read by BaseILEnv to slice the action
        # tensor consumed by the Pink controller back into per-arm poses.
        self.eef_action_slices = {
            "chess": {"pos": (0, 3), "quat": (3, 7)},
        }

        # Contiguous gripper index ranges per EEF.
        self.eef_gripper_slices = {
            "chess": (7, 8),
        }

        super().__post_init__()

        # Sim defaults from the task YAML (override BaseILEnvCfg defaults).
        self.decimation = 4
        self.episode_length_s = 300.0
        self.sim.dt = 1/240.0
        self.sim.render_interval = 4
        # A driven articulation must solve contact after its joint drives;
        # otherwise the stiff gripper drive can overwrite the contact impulse
        # and advance a jaw through a small dynamic object in the same step.
        self.sim.physx.solve_articulation_contact_last = True
        # Applying external forces on every TGS iteration multiplies the
        # contact-solve cost and is unnecessary for this position-driven arm.
        self.sim.physx.enable_external_forces_every_iteration = False
        # The original scene briefly required about 76 MB during contact-rich
        # startup. Keep headroom above that even though the collider overrides
        # above eliminate the pathological broad contact envelope.
        self.sim.physx.gpu_collision_stack_size = 2**27

        # Cameras — attached to robot links. Under XR teleop, IsaacLab's
        # `remove_camera_configs` strips these before scene build; the
        # `xr_camera_reattach` hook lets the teleop script put them back
        # before `gym.make` runs.
        attach_cameras(self.scene)
